name: Checkmarx SAST Scan on Merge
on:
  #pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: Checkmarx-cxflow-github-action-MergeAction # <-- Insert Checkmarx SAST Project Name
        team: /CxServer # default is /CxServer/SP/Company
        checkmarx_url: ${{ secrets.CHECKMARX_SERVER }}  # default is 
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}   # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sast #,sca  #should look like scanners: sast, sca and uncomment scan secrets 
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
        # sca_api_url: https://api.scacheckmarx.com # optional, default is https://api.scacheckmarx.com
        # Provide SCA APP URL
        # sca_app_url: https://sca.scacheckmarx.com # optional, default is https://sca.scacheckmarx.com
        # Provide SCA Access Control URL
        # sca_access_control_url: https://platform.checkmarx.net # optional, default is https://platform.checkmarx.net
        # Provide SCA Tenant
        # sca_tenant: ${{ secrets.SCA_TENANT }}  # optional, default is sca-champions
        # Provide SCA Username
        # sca_username: ${{ secrets.SCA_USERNAME }}   # optional, default is 
        # Provide SCA Password
        # sca_password: ${{ secrets.SCA_PASSWORD }} # optional, default is 
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif
